name: Docker Build API

on:
  workflow_dispatch:

jobs:
  docker-build-api:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Image (API)
        run: docker build -f DevOps/Docker/Dockerfile.api -t ai-api:latest .
