name: Docker Build Blazor

on:
  workflow_dispatch:

jobs:
  docker-build-blazor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image (Blazor)
        run: docker build -f DevOps/Docker/Dockerfile.blazor -t ai-blazor:latest .
