name: Docker Build CLI App

on:
  workflow_dispatch:

jobs:
  docker-build-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image (CLI)
        run: docker build -f DevOps/Docker/Dockerfile.cli -t ai-cli:latest .
